dist: xenial

cache: pip
# Set the build language to Python
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: 3.8
      arch: arm64

install: pip install -r requirements.txt

script:
  - python -m pytest --flake8 tests/
  - tox